"""initial_schema

Revision ID: d77653bc09db
Revises: 
Create Date: 2026-05-22 14:44:50.187348+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77653bc09db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_dashboard_cache_cache_key'), 'dashboard_cache', ['cache_key'], unique=True, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_dashboard_cache_id'), 'dashboard_cache', ['id'], unique=False, schema='qbe_demo')
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_departments_id'), 'departments', ['id'], unique=False, schema='qbe_demo')
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender', schema='qbe_demo'), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('insurance_provider', sa.String(length=100), nullable=True),
    sa.Column('insurance_number', sa.String(length=50), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_patients_email'), 'patients', ['email'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_patients_id'), 'patients', ['id'], unique=False, schema='qbe_demo')
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_services_id'), 'services', ['id'], unique=False, schema='qbe_demo')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='userrole', schema='qbe_demo'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_users_email'), 'users', ['email'], unique=True, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_users_id'), 'users', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_users_username'), 'users', ['username'], unique=True, schema='qbe_demo')
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['qbe_demo.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='qbe_demo')
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['qbe_demo.departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_employees_department_id'), 'employees', ['department_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_employees_id'), 'employees', ['id'], unique=False, schema='qbe_demo')
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'cancelled', 'overdue', name='invoicestatus', schema='qbe_demo'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['qbe_demo.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_invoices_due_date'), 'invoices', ['due_date'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_invoices_id'), 'invoices', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_invoices_patient_id'), 'invoices', ['patient_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_invoices_status'), 'invoices', ['status'], unique=False, schema='qbe_demo')
    op.create_table('query_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tables_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['qbe_demo.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_query_history_id'), 'query_history', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_query_history_user_id'), 'query_history', ['user_id'], unique=False, schema='qbe_demo')
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', 'no_show', name='appointmentstatus', schema='qbe_demo'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['qbe_demo.departments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['qbe_demo.employees.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['qbe_demo.patients.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['qbe_demo.services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_appointments_department_id'), 'appointments', ['department_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_appointments_id'), 'appointments', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_appointments_patient_id'), 'appointments', ['patient_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_appointments_service_id'), 'appointments', ['service_id'], unique=False, schema='qbe_demo')
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['qbe_demo.invoices.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['qbe_demo.services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_invoice_items_id'), 'invoice_items', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_invoice_items_service_id'), 'invoice_items', ['service_id'], unique=False, schema='qbe_demo')
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'insurance', 'bank_transfer', name='paymentmethod', schema='qbe_demo'), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['qbe_demo.invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_payments_id'), 'payments', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_payments_invoice_id'), 'payments', ['invoice_id'], unique=False, schema='qbe_demo')
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='ticketstatus', schema='qbe_demo'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('is_satisfied', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['qbe_demo.query_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['qbe_demo.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_tickets_id'), 'tickets', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_tickets_query_id'), 'tickets', ['query_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_tickets_status'), 'tickets', ['status'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_tickets_user_id'), 'tickets', ['user_id'], unique=False, schema='qbe_demo')
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('consultation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['qbe_demo.appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['qbe_demo.employees.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['qbe_demo.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_consultations_appointment_id'), 'consultations', ['appointment_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_consultations_id'), 'consultations', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_consultations_patient_id'), 'consultations', ['patient_id'], unique=False, schema='qbe_demo')
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['qbe_demo.invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['qbe_demo.payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='qbe_demo'
    )
    op.create_index(op.f('ix_qbe_demo_receipts_id'), 'receipts', ['id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_receipts_invoice_id'), 'receipts', ['invoice_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_receipts_payment_id'), 'receipts', ['payment_id'], unique=False, schema='qbe_demo')
    op.create_index(op.f('ix_qbe_demo_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=True, schema='qbe_demo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qbe_demo_receipts_receipt_number'), table_name='receipts', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_receipts_payment_id'), table_name='receipts', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_receipts_invoice_id'), table_name='receipts', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_receipts_id'), table_name='receipts', schema='qbe_demo')
    op.drop_table('receipts', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_consultations_patient_id'), table_name='consultations', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_consultations_id'), table_name='consultations', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_consultations_doctor_id'), table_name='consultations', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_consultations_appointment_id'), table_name='consultations', schema='qbe_demo')
    op.drop_table('consultations', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_tickets_user_id'), table_name='tickets', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_tickets_ticket_number'), table_name='tickets', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_tickets_status'), table_name='tickets', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_tickets_query_id'), table_name='tickets', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_tickets_id'), table_name='tickets', schema='qbe_demo')
    op.drop_table('tickets', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_payments_invoice_id'), table_name='payments', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_payments_id'), table_name='payments', schema='qbe_demo')
    op.drop_table('payments', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_invoice_items_service_id'), table_name='invoice_items', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_invoice_items_invoice_id'), table_name='invoice_items', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_invoice_items_id'), table_name='invoice_items', schema='qbe_demo')
    op.drop_table('invoice_items', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_appointments_service_id'), table_name='appointments', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_appointments_patient_id'), table_name='appointments', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_appointments_id'), table_name='appointments', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_appointments_doctor_id'), table_name='appointments', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_appointments_department_id'), table_name='appointments', schema='qbe_demo')
    op.drop_table('appointments', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_query_history_user_id'), table_name='query_history', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_query_history_id'), table_name='query_history', schema='qbe_demo')
    op.drop_table('query_history', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_invoices_status'), table_name='invoices', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_invoices_patient_id'), table_name='invoices', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_invoices_invoice_number'), table_name='invoices', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_invoices_id'), table_name='invoices', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_invoices_due_date'), table_name='invoices', schema='qbe_demo')
    op.drop_table('invoices', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_employees_id'), table_name='employees', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_employees_department_id'), table_name='employees', schema='qbe_demo')
    op.drop_table('employees', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_audit_logs_user_id'), table_name='audit_logs', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_audit_logs_id'), table_name='audit_logs', schema='qbe_demo')
    op.drop_table('audit_logs', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_users_username'), table_name='users', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_users_id'), table_name='users', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_users_email'), table_name='users', schema='qbe_demo')
    op.drop_table('users', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_services_id'), table_name='services', schema='qbe_demo')
    op.drop_table('services', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_patients_id'), table_name='patients', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_patients_email'), table_name='patients', schema='qbe_demo')
    op.drop_table('patients', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_departments_id'), table_name='departments', schema='qbe_demo')
    op.drop_table('departments', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_dashboard_cache_id'), table_name='dashboard_cache', schema='qbe_demo')
    op.drop_index(op.f('ix_qbe_demo_dashboard_cache_cache_key'), table_name='dashboard_cache', schema='qbe_demo')
    op.drop_table('dashboard_cache', schema='qbe_demo')
    # ### end Alembic commands ###
